language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: 
  - tiddlywiki ./*wiki --listen &
  - chmod +x push_back.sh
  - bash -c 'while [ 0 ]; do ./push_back.sh; sleep 60; done' &
  - ssh -o "StrictHostKeyChecking=no" -R 80:127.0.0.1:8080 ssh.localhost.run

after_success:

branches:
  only:
    - master
