language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: 
  - tiddlywiki ./*wiki --listen &
  - watch -n 240 ./push_back.sh &
  - ssh -o "StrictHostKeyChecking=no" -R 80:127.0.0.1:8080 ssh.localhost.run

after_success:

branches:
  only:
    - master
